### ISSUE TITLE
社交里部分设置不能生效

### ISSUE THREAD

**Issue by suikascarlet** [qyxtim/bitcron-pro#9]
社交部分，telegram链接不显示，mail显示图标但是跳转到404，希望能改一下

**Comment by yuxqiu** [comment]
感谢您反馈问题，telegram 的问题已修复了；关于 mail 显示图标但是跳转到404的问题，您可以去网上了解一下 mailto 格式。按照 mailto 格式填写不会出现这种问题。

**Comment by suikascarlet** [comment]
诶，惊叹于作者如此高效的修
可是，下载了最新的主题发现telegram的问题还是依旧，是有哪里设置需要注意的么？
mail的问题是我输入法搞出来的中文冒号的问题，谢谢提醒mailto格式
另外，又发现一个问题：
特殊功能如果关闭了，那么在其base setting页面点保存后会自动打开，所以无论特殊功能是否打开，在base setting页面点两次保存最终的状态都是打开的。
最后，在您自己的博客里漂浮着的小圆点如何设置？定义class="round-shape-one"？代码加到哪里比较合适？谢谢！

**Comment by yuxqiu** [comment]
telegram 的问题刚刚又提交了一版，已近彻底解决了。
关于 basic setting 的问题我刚刚测试了一下，确实会这样，我猜测这跟 gridea 软件本身的原因有关，这在主题里面无法进行调整。
如果您想定义 `round-shape-one` 这个 class，您可以像我的博客一样创建一个 div 放在 `<div class="post_list" >` 下面。还要加上如下的 css 才能实现漂浮的原点效果

```css
.round-shape-one {
    width: 20px;
    height: 20px;
    border: 3px solid #fe8f8f;
    border-radius: 50%;
    top: 15%;
    left: 0;
    -webkit-animation: animationFramesOne 15s infinite linear;
    animation: animationFramesOne 15s infinite linear
}
@keyframes animationFramesOne {
    0% {
        transform: translate(0) rotate(0deg)
    }
    20% {
        transform: translate(73px, -1px) rotate(36deg)
    }
    40% {
        transform: translate(141px, 72px) rotate(72deg)
    }
    60% {
        transform: translate(83px, 122px) rotate(108deg)
    }
    80% {
        transform: translate(-40px, 72px) rotate(144deg)
    }
    to {
        transform: translate(0) rotate(0deg)
    }
}
```
